### ISSUE TITLE
no space error after upgrading to 2.9.0.210

### ISSUE THREAD

**Issue by loughnane** [juruen/rmapi#197]
Was uploading some things just fine this morning then an automatic (beta) update kicked in and now I'm getting the error below whenever I try to upload. My device is using 4.24 GB of the 6.41GB available so there is plenty of space.

    
    $: sudo ../../rmapi put BOOK.TO.UPLOAD.epub /books
    uploading: [BOOK.TO.UPLOAD.epub]...ERROR: 2021/08/12 08:24:17 zipdoc.go:137: failed to create content entry in zip file write /tmp/rmapizip091664885: no space left on device
    ERROR: 2021/08/12 08:24:17 api.go:244: failed to create zip doc write /tmp/rmapizip091664885: no space left on device
    ERROR: 2021/08/12 08:24:17 main.go:18: Error:  Failed to upload file [BOOK.TO.UPLOAD.epub] write /tmp/rmapizip091664885: no space left on device

**Comment by ddvk** [comment]
you dont have space on your local /tmp drive
also don't use sudo

**Comment by ddvk** [comment]
not a problem with rmapi
